### ISSUE TITLE
Patch for Downloader

### ISSUE THREAD

**Issue by jposterloh** [MasterEx/jupar#1]
Hi, 

if you are interested, I fixed for myself two issues:
1) DownloaderXMLParserHandler: I had a longer list of files to download, and this failed after some files, because of a truncated filename (i.e. the url was cropped). After having a look at DownloaderXMLParserHandler, I figured out that the "ch" array in characters was full, and the rest of the filename came with the next call of characters. I fixed this by caching the value from characters until `endElement` is called. 
2) The second one was more a convenience fix, I changed the copy function in Update so that it checks if destination is a directory, and if to append the filename to the destination. With that, you can now just give the destination directory in the MOVE instruction. 

Best regards
Jan-Patrick

[jupar.zip](https://github.com/MasterEx/jupar/files/1092155/jupar.zip)

**Comment by MasterEx** [comment]
Hi Jan-Patrick.

Thank you for your changes. I have merged them in 7d8a7f037f38986aa28.
